dist: bionic
language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - libstdc++-10-dev
      env: CXX=g++-10 BUILD_TYPE=Release SANITIZER=false

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - libstdc++-10-dev
      env: CXX=g++-10 BUILD_TYPE=Debug SANITIZER=false
      
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-9
            - libstdc++-9-dev
      env: CXX=clang++-9 BUILD_TYPE=Release SANITIZER=false

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-9
            - libstdc++-9-dev
      env: CXX=clang++-9 BUILD_TYPE=Debug SANITIZER=false

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-10
            - libstdc++-10-dev
      env: CXX=clang++-10 BUILD_TYPE=Release SANITIZER=false

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-10
            - libstdc++-10-dev
      env: CXX=clang++-10 BUILD_TYPE=Debug SANITIZER=false

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-11
            - libstdc++-11-dev
      env: CXX=clang++-11 BUILD_TYPE=Release SANITIZER=false

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-11
            - libstdc++-11-dev
      env: CXX=clang++-11 BUILD_TYPE=Debug SANITIZER=true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt install libicu-dev libicu60 libxml2-dev
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/DEPS"
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}


install:
  - |
    CMAKE_URL="https://cmake.org/files/v3.18/cmake-3.18.1-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - |
  - install_boost.sh ${DEPS_DIR}
  - |
    GOOGLETEST_URL="https://github.com/google/googletest/archive/release-1.10.0.tar.gz"
    mkdir googletest && travis_retry wget --no-check-certificate --quiet -O - ${GOOGLETEST_URL} | tar --strip-components=1 -xz -C googletest
  - cd googletest
  - cmake -DBUILD_SHARED_LIBS=ON -j4 .
  - make -j4
  - sudo cp -a googletest/include/gtest /usr/include
  - sudo cp -a lib/libgtest_main.so lib/libgtest.so /usr/lib/
  - sudo make install


before_script:
  - export PATH=${DEPS_DIR}/boost:${PATH}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd ${TRAVIS_BUILD_DIR}


script:
  - pwd
  - uname -a
  - cmake --version
  - ${CXX} --version
  - cmake -DPDL_WITH_TESTS=1 -DPDL_WITH_SANITIZER=${SANITIZER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX} -j4 .
  - make -j4
  - ctest --verbose


notifications:
  email:
    on_failure: always
    on_success: never
