name: CMake

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}

    strategy:
      fail-fast: false

      matrix:
        config:
        - {
            name: "GCC 11 Release",
            build_type: "Release",
            compiler: "g++-11",
            generators: "Unix Makefiles"
          }
        - {
            name: "GCC 11 Debug",
            build_type: "Debug",
            compiler: "g++-11",
            generators: "Unix Makefiles"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Set common repository and keys
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt install wget
        sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get -qq update
        sudo apt install libicu-dev libicu66 libxml2-dev zlib1g-dev
        DEPS_DIR="${{ github.workspace }}/DEPS"
        mkdir -p ${DEPS_DIR}

    - name: Install GCC 11
      run: |
        sudo apt install build-essential cmake
        sudo apt install gcc-11 g++-11 libstdc++-11-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

    - name: Build LLVM
      env:
        CC: /usr/bin/gcc
        CXX: /usr/bin/g++
      run: |
        ${CXX} --version
        cd ${{ github.workspace }}
        sudo chmod +x install_llvm.sh
        sudo sh ./install_llvm.sh ${DEPS_DIR}
        export PATH=${DEPS_DIR}/llvm:${PATH}

    - name: Build Boost
      env:
        CC: /usr/bin/gcc
        CXX: /usr/bin/g++
      run: |
        cd ${{ github.workspace }}
        sudo chmod +x install_boost.sh
        sudo sh ./install_boost.sh ${DEPS_DIR}
        export PATH=${DEPS_DIR}/boost:${PATH}

    - name: Build GTest
      run: |
        cd ${{ github.workspace }}
        sudo chmod +x install_gtest.sh
        sudo sh ./install_gtest.sh ${DEPS_DIR}
        export PATH=${DEPS_DIR}/gtest:${PATH}

    - name: Configure CMake
      run: |
        cd ${{ github.workspace }}
        pwd
        uname -a
        cmake --version
        ${CXX} --version
        cmake -DPDL_WITH_TESTS=1 -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_CXX_COMPILER=${CXX} .

    - name: Build
      run: cmake --build ${{ github.workspace }}/build -j "$(nproc)"

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --verbose
