name: CMake

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}

    strategy:
      fail-fast: false

      matrix:
        config:
        - {
            name: "Clang 9 Release",
            build_type: "Release",
            cc: "clang-9",
            cxx: "clang++-9",
            generators: "Unix Makefiles"
          }
        - {
            name: "Clang 9 Debug",
            build_type: "Debug",
            cc: "clang-9",
            cxx: "clang++-9",
            generators: "Unix Makefiles"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Set common repository and keys
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt install wget
        sudo wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get -qq update
        sudo apt install libicu-dev libicu60 libxml2-dev zlib1g-dev
        DEPS_DIR="./DEPS"
        mkdir -p ${DEPS_DIR}

    - name: Install Clang 9
      if: startsWith(matrix.config.cc, 'clang-9')
      run: |
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt-get -qq update
        sudo apt install clang-9 libstdc++-9-dev
        clang-9 --version
        export CC=clang-9
        export CXX=clang++-9

    - name: Build CMake
      run: |
        CMAKE_URL="https://cmake.org/files/v3.20/cmake-3.20.2-linux-x86_64.tar.gz"
        mkdir cmake && wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    - name: Build Boost
      run: |
        install_boost.sh ${DEPS_DIR}
        export PATH=${DEPS_DIR}/boost:${PATH}

    - name: Build LLVM
      run: |
        install_llvm.sh ${DEPS_DIR}
        export PATH=${DEPS_DIR}/llvm:${PATH}

    - name: Build GTest
      run: |
        install_gtest.sh ${DEPS_DIR}
        export PATH=${DEPS_DIR}/gtest:${PATH}

    - name: Configure CMake
      run: |
        cd ${{ github.workspace }}
        pwd
        uname -a
        cmake --version
        ${CXX} --version
        cmake -DPDL_WITH_TESTS=1 -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_CXX_COMPILER=${CXX} .

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{ github.workspace }}/build -j "$(nproc)"

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --verbose
